#
# This source file is part of the CardinalKit open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: CardinalKit-Package.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: CardinalKit-Package
  buildandtestuitests:
    name: Build and Test
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: Balance.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      setupfirebaseemulator: true
      customcommand: "firebase emulators:exec 'set -o pipefail && xcodebuild test -project Tests/UITests/UITests.xcodeproj -scheme TestApp -destination "name=iPhone 14 Pro Max" -resultBundlePath UITests.xcresult CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty'"
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest, buildandtestuitests]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: CardinalKit-Package.xcresult TestApp.xcresult
