#
# This source file is part of the CardinalKit open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: CardinalKit-Package.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      customcommand: |
          xcodebuild \
            -scheme CardinalKit-Package \
            -resolvePackageDependencies \
            -list \
            -derivedDataPath ".derivedData"
          set -o pipefail \
            && xcodebuild test \
              -scheme CardinalKit-Package \
              -sdk iphonesimulator \
              -destination "name=iPhone 14 Pro Max" \
              -enableCodeCoverage YES \
              -derivedDataPath ".derivedData" \
              -resultBundlePath CardinalKit-Package.xcresult \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
            | xcpretty
  buildandtestuitests:
    name: Build and Test
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: TestApp.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      setupfirebaseemulator: true
      customcommand: |
          cd Tests/UITests
          firebase emulators:exec 'set -o pipefail && xcodeect UITests.xcodeproj -scheme TestApp -destination "name=iPhone 14 Pro Max" -resultBundlePath UITests.xcresult CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty'
          mv UITests.xcresult ../../UITests.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest, buildandtestuitests]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: CardinalKit-Package.xcresult TestApp.xcresult
